name: news-bulletin-playlist

services:
  app:
    image: ghcr.io/experience83/news-bulletin-playlist:edge-amd64
    restart: unless-stopped
    init: true
    user: "568:568"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: "Europe/Madrid"
    ports:
      - "0.0.0.0:8788:8080"
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16m
    volumes:
      - type: bind
        source: /mnt/Pool1/news-bulletin-playlist
        target: /data
        bind:
          create_host_path: false
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
    pids_limit: 128
    stop_grace_period: 15s

x-portals:
  - host: 0.0.0.0
    name: "Web UI"
    path: /
    port: 8788
    scheme: http
